### ISSUE TITLE
build error, vcg::TriEdgeCollapseQuadricParameter error

### ISSUE THREAD

**Issue by Arsakes** [cfcohen/openbrf#2]
Build attempted on archlinux - build script from AUR ([link](https://aur.archlinux.org/packages/openbrf/))

```
g++ -c -pipe -std=c++0x -isystem ../vcglib -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wall -W -D_REENTRANT -DGLEW_STATIC -DQT_NO_DEBUG -DQT_XML_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtXml -I/usr/include/qt4 -Ilib3ds-1.3.0 -I. -I/usr/X11R6/include -Itmp -Itmp -o askModErrorDialog.o askModErrorDialog.cpp
vcgmesh.cpp: In static member function ‘static int VcgMesh::simplify(int)’:
vcgmesh.cpp:209:10: error: ‘class vcg::tri::TriEdgeCollapseQuadricParameter’ has no member named ‘SafeHeapUpdate’
  qparams.SafeHeapUpdate = true;
          ^~~~~~~~~~~~~~
```

**Comment by infomatec** [comment]
Same thing in Linux Mint 

> vcgmesh.cpp: In static member function ‘static int VcgMesh::simplify(int)’:
> vcgmesh.cpp:209:10: error: ‘class vcg::tri::TriEdgeCollapseQuadricParameter’ has no member named ‘SafeHeapUpdate’
>   qparams.SafeHeapUpdate = true;

**Comment by Arsakes** [comment]
Any progress here?

**Comment by cfcohen** [comment]
I wasn't actually watching this repo for issues, since I ported this code to Linux on a whim just so I could view the Mount & Blade assets.   My distribution of VCG defines SafeHeapUpdate in vcg::tri::TriEdgeCollapseQuadricParameter (in complex/algorithms/local_optimization/tri_edge_collapse_quadric.h), so it would appear to a problem with VCG updates since I ported the code.

**Comment by cfcohen** [comment]
I've updated the repo with upstream changes which apparently included commenting out the offending line of code.   Hopefully that change has resolved your issue as well.
